### ISSUE TITLE
Potential Enhancements

### ISSUE THREAD

**Issue by j042** [tataratat/splinepy#25]
# Potential Enhancements
Features and good/cool ideas can be documented and discussed here. This main part will be updated regularly.
_last update: 06.10.2022_

- [x] N-dim bezier operations
- [x] Multithread executions for all queries
- [x] Dynamic cmake build
- [x] Explicit instantiation of some template classes for faster compilation (develop)
- [ ] One example for each functionalities.
- [x] static fitting functions (#24)
- [ ] Enhance IO, especially mfem, (#31)
- [x] Boundary spline extraction, especially useful for proximity queries.
- [x] cmake extension - real packaging for cpp use

**Comment by jzwar** [comment]
Some additional remarks (_**HackDayzz**_:tm: - potential):
- [ ] **So many warnings** :exclamation:  When building splinepy, so many warnings are produced, this is largely avoidable and shows bad practice if we leave it like that
- [ ] Enhance IO, especially for mfem, see maybe Issue #31
